name: luna
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyyaml
  - h5py
  - pip
  - pip:
      - pywavelets
      - scikit-learn
      - torch
      - pytest
