#!/usr/bin/env python3
"""
=============================================================================
P0 consolidation — package P0-1 (analytical benchmark) + P0-2 (wavelet
sensitivity) into the paper build conventions.
=============================================================================

Purpose
-------
Turn the raw P0 results into a "patch" the paper team can consume when
restructuring the manuscript (work-list 20260826: Stage 3 = analytical
validation; Stage 8 / P1-6 = wavelet sensitivity / methodology).

Outputs (flat under build/data/ — no p0 subfolder)
-------
  build/data/p0_patch_README.md           — consumption guide (paper patch doc)
  build/data/p0_consolidated.json         — curated single-source P0 numbers
  build/data/p0_consolidated.csv          — flat table of the same numbers
  build/data/p0_facts.yaml                — paper_facts-style YAML (+ proposed
                                            LaTeX macro names \F...)
  build/generated/tables/tab_analytical_benchmark.tex  — P0-1 table body
  build/generated/tables/tab_wavelet_family_sensitivity.tex   — P0-2 table body
  (figures already at build/figures/fig_analytical_benchmark.{pdf,png} and
   fig_wavelet_sensitivity.{pdf,png}; this script registers them + tables in
   build/figures_tables_registry.csv)

Inputs (raw results, generated by compute_p0_analytical.py and
compute_p0_2_wavelet_sensitivity.py)
-------
  artifacts/derived/main/statistics/analytical_benchmark.json
  artifacts/derived/main/statistics/wavelet_sensitivity.json

Usage
-----
  conda run -n sana python applications/paper_main/analyses/_canonical/consolidate_p0.py
=============================================================================
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import numpy as np
import yaml

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from luna.core.constants import BANDS_CF

STATS_DIR = _PROJECT_ROOT / "artifacts" / "derived" / "main" / "statistics"
DATA_DIR = _PROJECT_ROOT / "applications" / "paper_main" / "build" / "data"
P0_DIR = DATA_DIR  # flat: P0 products live directly in build/data/ (no p0/ subfolder)
TABLES_DIR = _PROJECT_ROOT / "applications" / "paper_main" / "build" / "generated" / "tables"
REGISTRY = _PROJECT_ROOT / "applications" / "paper_main" / "build" / "figures_tables_registry.csv"
FIG_DIR = _PROJECT_ROOT / "applications" / "paper_main" / "build" / "figures"

WAVELETS = ["haar", "db2", "db4", "sym4", "coif1"]
MODELS = ["ridge", "mlp", "vcnn"]
MODEL_LABEL = {"ridge": "Ridge", "mlp": "MLP", "vcnn": "VCNN"}
CASES = ["A_full", "B_del_W1", "C_del_W1W2", "D_del_W3", "E1_del_W1_only", "E2_partial_W3"]
CASE_LABEL = {"A_full": "A (full)", "B_del_W1": "B (del W1)", "C_del_W1W2": "C (del W1,W2)",
              "D_del_W3": "D (del W3)", "E1_del_W1_only": "E1 (del W1)",
              "E2_partial_W3": "E2 (partial W3)"}
EXPECTED = {"A_full": 5, "B_del_W1": 4, "C_del_W1W2": 3, "D_del_W3": 2,
            "E1_del_W1_only": 4, "E2_partial_W3": 2}

TAB_HEADER = (
    "% !! 自动生成 — 勿手改 !!\n"
    "% 生成器: applications/paper_main/analyses/_canonical/consolidate_p0.py\n"
    "% 真值源: artifacts/derived/main/statistics/analytical_benchmark.json + wavelet_sensitivity.json\n"
)


# ══════════════════════════════════════════════════════════════════════
# Load raw results
# ══════════════════════════════════════════════════════════════════════
def load() -> tuple[dict, dict]:
    ab = json.loads((STATS_DIR / "analytical_benchmark.json").read_text(encoding="utf-8"))
    ws = json.loads((STATS_DIR / "wavelet_sensitivity.json").read_text(encoding="utf-8"))
    return ab, ws


# ══════════════════════════════════════════════════════════════════════
# Curated consolidated structure
# ══════════════════════════════════════════════════════════════════════
def build_consolidated(ab: dict, ws: dict) -> dict:
    stats = ab["ensemble_stats"]
    rep = ab["representative_seed0"]
    return {
        "meta": {
            "package": "P0 patch: analytical multiscale benchmark + wavelet sensitivity",
            "worklist_ref": "20260826 P0-1 / P0-2",
            "grid": ab.get("grid"),
            "wavelet": ab.get("wavelet"),
            "tau": ab.get("tau"),
            "params": ab.get("params"),
            "wavenum": ab.get("wavenum"),
        },
        "p0_1": {
            "target_band_energy_fractions": ab.get("target_band_energy_fractions"),
            "nc_reference_band_energy_fractions": {
                "A4": 0.966, "W4": 0.029, "W3": 0.004, "W2": 0.001, "W1": 0.000},
            "cases": {
                c: {
                    "expected_S_full": EXPECTED[c],
                    "GER_mean": stats[c]["GER_mean"],
                    "GER_std": stats[c]["GER_std"],
                    "S_full_mean": stats[c]["S_full_mean"],
                    "S_full_std": stats[c]["S_full_std"],
                    "S_full_correct_frac": stats[c]["S_full_correct_frac"],
                    "S_coh_mean": stats[c].get("S_coh_mean"),
                    "E_direct_mean": stats[c]["E_direct_mean"],
                    "E_direct_std": stats[c]["E_direct_std"],
                }
                for c in CASES
            },
            "representative_seed0": {
                c: {"GER": rep[c]["GER"], "S_full": rep[c]["S_full"],
                    "S_coh": rep[c]["S_coh"], "E_direct": rep[c]["E_direct"]}
                for c in CASES
            },
            "case_E_matched_GER": {
                "E1_GER": stats["E1_del_W1_only"]["GER_mean"],
                "E2_GER": stats["E2_partial_W3"]["GER_mean"],
                "E1_S_full": stats["E1_del_W1_only"]["S_full_mean"],
                "E2_S_full": stats["E2_partial_W3"]["S_full_mean"],
                "finding": "identical GER, S_full 4 vs 2 (same GER != same scales)",
            },
        },
        "p0_2": {
            "representative_case": ws.get("representative_case"),
            "real_nc": {
                wt: {
                    m: {
                        "GER_mean": ws["real_nc"][wt][m]["GER_mean"],
                        "S_full_mean": ws["real_nc"][wt][m]["S_full_mean"],
                        "S_full_mode": ws["real_nc"][wt][m]["S_full_mode"],
                        "S_full_dist": ws["real_nc"][wt][m]["S_full_dist"],
                        "S_coh_mode": ws["real_nc"][wt][m]["S_coh_mode"],
                        "E_direct_mean": ws["real_nc"][wt][m]["E_direct_mean"],
                    }
                    for m in MODELS
                }
                for wt in WAVELETS
            },
            "analytical_benchmark_detection": {
                wt: {c: ws["analytical_benchmark"][wt][c]["correct_frac"]
                     for c in CASES}
                for wt in WAVELETS
            },
            "headline_findings": {
                "mlp_vcnn_robust": "S_full=5 for MLP and VCNN across all 5 wavelets",
                "ridge_robust_smooth": "Ridge fine-band failure (S_full mode 2-3) holds for db2/db4/sym4/coif1",
                "haar_outlier": "haar smears Ridge S_full (mode 5, bimodal) -> poor octave selectivity, unsuitable",
                "hierarchy_consistent": "coarse-to-fine error hierarchy qualitatively consistent in all wavelets",
                "analytical_detection": "P0-1 benchmark detection 100% for db2/db4/sym4/coif1, 93% for haar",
            },
        },
    }


# ══════════════════════════════════════════════════════════════════════
# LaTeX tables
# ══════════════════════════════════════════════════════════════════════
def fmt(v: float, n: int = 4) -> str:
    return f"{float(v):.{n}f}"


def table_analytical_benchmark(cons: dict) -> str:
    cases = cons["p0_1"]["cases"]
    lines = [TAB_HEADER,
             r"\begin{tabular}{lcccccc}",
             r"  \toprule",
             r"  Case & $\Sfull^{\mathrm{exp}}$ & \GER{} & $\Sfull$ & $\Scoh$ & Corr. \\",
             r"  \midrule"]
    for c in CASES:
        d = cases[c]
        scoh = f"{d['S_coh_mean']:.1f}" if d.get("S_coh_mean") is not None else "---"
        lines.append(
            f"  {CASE_LABEL[c]} & {d['expected_S_full']} & {fmt(d['GER_mean'])} "
            f"& {fmt(d['S_full_mean'], 1)} & {scoh} & {fmt(d['S_full_correct_frac'], 2)} \\\\"
        )
    lines += [r"  \bottomrule", r"\end{tabular}"]
    lines += ["", r"\medskip", "", TAB_HEADER,
              r"\begin{tabular}{lcccccc}",
              r"  \toprule",
              r"  Case & A4 & W4 & W3 & W2 & W1 \\",
              r"  \midrule"]
    fracs = cons["p0_1"]["target_band_energy_fractions"]
    for c in CASES:
        d = cases[c]
        lines.append("  " + CASE_LABEL[c] + " & "
                     + " & ".join(fmt(d["E_direct_mean"][b]) for b in BANDS_CF) + r" \\")
    lines.append(r"  \midrule")
    lines.append(r"  Target $\omega_b$ & " + " & ".join(fmt(fracs[b], 3) for b in BANDS_CF) + r" \\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def table_wavelet_sensitivity(cons: dict) -> str:
    nc = cons["p0_2"]["real_nc"]
    lines = [TAB_HEADER,
             r"\begin{tabular}{llcccccccc}",
             r"  \toprule",
             r"  Wavelet & Model & \makecell{$\Sfull$\\mode} & \makecell{$\Scoh$\\mode} & \GER{}"
             r" & A4 & W4 & W3 & W2 & W1 \\",
             r"  \midrule"]
    for wt in WAVELETS:
        for m in MODELS:
            d = nc[wt][m]
            errs = " & ".join(fmt(d["E_direct_mean"][b], 3) for b in BANDS_CF)
            lines.append(f"  {wt} & {MODEL_LABEL[m]} & {d['S_full_mode']} & {d['S_coh_mode']} "
                         f"& {fmt(d['GER_mean'])} & {errs} \\\\")
        if wt != WAVELETS[-1]:
            lines.append(r"  \addlinespace")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    # analytical benchmark detection block
    det = cons["p0_2"]["analytical_benchmark_detection"]
    lines += ["", r"\medskip", "", TAB_HEADER,
              r"\begin{tabular}{lcccccc}",
              r"  \toprule",
              r"  Wavelet & \makecell{analytical case A\\correct} & B & C & D & E1 & E2 \\",
              r"  \midrule"]
    for wt in WAVELETS:
        row = f"  {wt} & " + " & ".join(f"{det[wt][c]:.2f}" for c in CASES) + r" \\"
        lines.append(row)
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


# ══════════════════════════════════════════════════════════════════════
# paper_facts-style YAML with proposed macros
# ══════════════════════════════════════════════════════════════════════
def build_facts_yaml(cons: dict) -> str:
    s = cons["p0_1"]["cases"]
    nc = cons["p0_2"]["real_nc"]
    det = cons["p0_2"]["analytical_benchmark_detection"]
    facts = {
        "# header": "# =============================================================================\n"
                    "# p0_facts.yaml — P0 patch 数值事实 (合并进 paper_facts.yaml 用)\n"
                    "# 建议的 LaTeX 宏名已标注 (proposed_macro)。合并时在 generate_paper_numbers.py\n"
                    "# 的 MACRO_MAP 增加对应条目即可。",
        "p0_1": {
            "grid": {"H": 80, "W": 160, "x0": 28.0, "y0": 40.0, "kind": "config"},
            "band_energy_fractions": {
                "value": cons["p0_1"]["target_band_energy_fractions"],
                "kind": "result", "status": "verified",
                "source": "artifacts/derived/main/statistics/analytical_benchmark.json",
                "note": "解析场 band 能量层级, 复现真实 NC (A4~95% 主导)",
                "proposed_macro": "FPZeroBandFrac",
            },
            "nc_reference_band_energy_fractions": {
                "value": cons["p0_1"]["nc_reference_band_energy_fractions"],
                "kind": "result", "status": "verified", "source": "data/cylinder2d_q1.npy",
                "note": "真实 NC u-field band 能量 (200 帧均值)",
                "proposed_macro": "FPZeroNCBandFrac",
            },
            "cases": {
                c: {
                    "expected_S_full": s[c]["expected_S_full"],
                    "GER_mean": s[c]["GER_mean"],
                    "S_full_mean": s[c]["S_full_mean"],
                    "S_full_correct_frac": s[c]["S_full_correct_frac"],
                    "S_coh_mean": s[c]["S_coh_mean"],
                    "E_direct_mean": s[c]["E_direct_mean"],
                    "kind": "result", "status": "verified",
                    "source": "analytical_benchmark.json",
                    "proposed_macro": {"GER": f"FPZeroGER{_case_macro(c)}",
                                       "S_full_correct": f"FPZeroCorr{_case_macro(c)}",
                                       "S_full": f"FPZeroSFull{_case_macro(c)}"},
                }
                for c in CASES
            },
            "case_E_matched_GER": {
                **cons["p0_1"]["case_E_matched_GER"],
                "kind": "claim", "status": "verified",
                "proposed_macro": {"E1_GER": "FPZeroEOneGER", "E2_GER": "FPZeroETwoGER",
                                   "E1_S_full": "FPZeroEOneSFull", "E2_S_full": "FPZeroETwoSFull"},
            },
        },
        "p0_2": {
            "wavelets": {"value": WAVELETS, "kind": "config",
                         "proposed_macro": "FPTwoWavelets"},
            "representative_case": {"value": cons["p0_2"]["representative_case"],
                                    "kind": "config",
                                    "proposed_macro": "FPTwoRepCase"},
            "real_nc_S_full_mode": {
                "value": {wt: {m: nc[wt][m]["S_full_mode"] for m in MODELS} for wt in WAVELETS},
                "kind": "result", "status": "verified",
                "source": "wavelet_sensitivity.json",
                "note": "M=30, sigma=0, 300 test snapshots. MLP/VCNN=5 全鲁棒; "
                        "Ridge db2/db4/sym4/coif1 失效, haar 例外",
                "proposed_macro": "FPTwoSFullMode",
            },
            "ridge_failure_robust": {
                "value": {"db2": 2, "db4": 3, "sym4": 2, "coif1": 2, "haar": 5},
                "kind": "result", "status": "verified",
                "note": "Ridge 细尺度失效在平滑小波下稳健 (S_full mode 2-3); haar 抹平",
                "proposed_macro": "FPTwoRidgeMode",
            },
            "analytical_detection": {
                "value": {wt: {c: det[wt][c] for c in CASES} for wt in WAVELETS},
                "kind": "result", "status": "verified",
                "note": "P0-1 解析 benchmark 检测正确率: db2/db4/sym4/coif1=100%, haar~93%",
                "proposed_macro": "FPTwoAnaCorrect",
            },
            "headline_findings": {
                "value": cons["p0_2"]["headline_findings"],
                "kind": "claim", "status": "verified",
            },
        },
    }
    return yaml.safe_dump(facts, allow_unicode=True, sort_keys=False, width=100)


def _case_macro(c: str) -> str:
    return {"A_full": "A", "B_del_W1": "B", "C_del_W1W2": "C", "D_del_W3": "D",
            "E1_del_W1_only": "EOne", "E2_partial_W3": "ETwo"}[c]


# ══════════════════════════════════════════════════════════════════════
# README (patch consumption guide)
# ══════════════════════════════════════════════════════════════════════
README = """# P0 Patch — 新增实验的数据源与图源补丁

配套工作清单 `agent-docs/20260826.md` 的 **P0-1**（解析多尺度算例）与 **P0-2**
（wavelet-family 敏感性审计）。本目录是这两个新增实验的权威数据源与图源补丁，
供后续论文重构（Phase F/G）直接消费。

## 一、内容清单

| 文件 | 说明 |
| ---- | ---- |
| `p0_consolidated.json` | 权威整合数据（P0-1 全 case 指标 + P0-2 全 wavelet×model 指标） |
| `p0_consolidated.csv` | 同一数据的扁平表 |
| `p0_facts.yaml` | paper_facts 风格 YAML + 建议 LaTeX 宏名（合并进 `build/data/paper_facts.yaml`） |
| `p0_patch_README.md` | 本说明 |
| `../generated/tables/tab_analytical_benchmark.tex` | P0-1 表格主体（\input 用） |
| `../generated/tables/tab_wavelet_family_sensitivity.tex` | P0-2 表格主体（\input 用） |
| `../figures/fig_analytical_benchmark.{pdf,png}` | P0-1 主图（三部分：目标+band / 受控重建 / per-band 误差） |
| `../figures/fig_wavelet_sensitivity.{pdf,png}` | P0-2 图（模型排序 / Ridge 层级 / 解析检测热图） |

原始计算结果（脚本输入）：
`artifacts/derived/main/statistics/analytical_benchmark.{json,csv}`、
`artifacts/derived/main/statistics/wavelet_sensitivity.{json,csv}`。

## 二、P0-1 一句话结论（Stage 3: Analytical validation）

> 在答案完全已知的解析多尺度尾流中，`S_full`/`S_coh` 能 100% 正确识别
> 人为删除的尺度（del W1→4, del W1+W2→3, del W3→2, del W4→1）；
> Case E 证明 **相同 GER (0.019) 可以对应不同的可恢复尺度 (S_full 4 vs 2)**，
> 即 Scale Recoverability 提供 GER 无法提供的信息。

- 构造：streamfunction `psi = psi0 + E·Σ A_j g_j`，`u=∂ψ/∂y, v=−∂ψ/∂x`（divergence-free）
- 能量层级复现真实 NC（A4≈95%），100 快照 100% 正确；主图一张即可说明方法成立。
- 建议正文位置：方法验证节（真实 NC 之前），图 `fig_analytical_benchmark` + 表 `tab_analytical_benchmark`。

## 三、P0-2 一句话结论（Stage 8 / P1-6: wavelet sensitivity）

> 模型排序（Ridge ≪ MLP≈VCNN）与 coarse-to-fine 层级在 db2/db4/sym4/coif1
> 下定性一致（Ridge S_full mode 2–3，MLP/VCNN=5）；haar 因频率选择性差
> 会抹平 Ridge 的细尺度失效（mode 跳至 5），应列为框架适用性限制。

- P0-1 解析 benchmark 检测：db2/db4/sym4/coif1 100%，haar 93% → 解析验证非 db2 特异。
- 直接支撑 P1-6："framework 是 wavelet-family agnostic 的思想，但 band 边界与数值依赖 transform choice，且需要频率选择性足够的小波"。
- 建议正文位置：Robustness/definition sensitivity 节，图 `fig_wavelet_sensitivity` + 表 `tab_wavelet_family_sensitivity`。

## 四、合并进论文的步骤（Phase G 时）

1. 图：把 `../figures/fig_analytical_benchmark.pdf`、`../figures/fig_wavelet_sensitivity.pdf`
   复制到 thesis 仓 `thesis_src_planB/figures/`，正文 `\includegraphics` 引用。
2. 表：把 `../generated/tables/tab_analytical_benchmark.tex`、
   `tab_wavelet_family_sensitivity.tex` 复制到 thesis 仓 `generated/tables/`，
   正文 `\\input{{generated/tables/tab_xxx}}`（caption/label 留在正文）。
3. 数字宏：把 `p0_facts.yaml` 合并进 `build/data/paper_facts.yaml`，
   在 `build/tools_gen/generate_paper_numbers.py` 的 MACRO_MAP 增加
   `proposed_macro` 条目后重新生成 `paper_numbers.tex`。
4. Registry：`build/figures_tables_registry.csv` 已登记两个新图与两个新表。

## 五、复现命令

```bash
# 重新生成原始结果（耗时较长，P0-2 约 10 分钟）
conda run -n sana python applications/paper_main/analyses/_canonical/compute_p0_analytical.py
conda run -n sana python applications/paper_main/analyses/_canonical/compute_p0_2_wavelet_sensitivity.py
# 或仅重看 P0-2 摘要（不重算）
conda run -n sana python applications/paper_main/analyses/_canonical/compute_p0_2_wavelet_sensitivity.py --summary-only
# 重新整合本补丁
conda run -n sana python applications/paper_main/analyses/_canonical/consolidate_p0.py
```
"""


# ══════════════════════════════════════════════════════════════════════
# Registry
# ══════════════════════════════════════════════════════════════════════
REGISTRY_ROWS = [
    # paper_id, type, tex_location, script, facts_path, data_source, status, match, issues
    ("fig_analytical_benchmark.pdf", "figure", "NEW (Stage3 analytical validation)",
     "applications/paper_main/analyses/_canonical/compute_p0_analytical.py",
     "applications/paper_main/build/data/p0_facts.yaml",
     "artifacts/derived/main/statistics/analytical_benchmark.json", "NEW_P0", "OK", "P0-1"),
    ("fig_wavelet_sensitivity.pdf", "figure", "NEW (Stage8 wavelet sensitivity)",
     "applications/paper_main/analyses/_canonical/compute_p0_2_wavelet_sensitivity.py",
     "applications/paper_main/build/data/p0_facts.yaml",
     "artifacts/derived/main/statistics/wavelet_sensitivity.json", "NEW_P0", "OK", "P0-2"),
    ("tab_analytical_benchmark.tex", "table", "NEW (Stage3 analytical validation)",
     "applications/paper_main/analyses/_canonical/consolidate_p0.py",
     "applications/paper_main/build/data/p0_facts.yaml",
     "artifacts/derived/main/statistics/analytical_benchmark.json", "NEW_P0", "OK", "P0-1"),
    ("tab_wavelet_family_sensitivity.tex", "table", "NEW (Stage8 wavelet sensitivity)",
     "applications/paper_main/analyses/_canonical/consolidate_p0.py",
     "applications/paper_main/build/data/p0_facts.yaml",
     "artifacts/derived/main/statistics/wavelet_sensitivity.json", "NEW_P0", "OK", "P0-2"),
]


def update_registry() -> None:
    if not REGISTRY.exists():
        print(f"[warn] registry missing: {REGISTRY}")
        return
    lines = REGISTRY.read_text(encoding="utf-8").splitlines()
    header = lines[0]
    ids = {r[0] for r in REGISTRY_ROWS} | {"tab_wavelet_sensitivity.tex"}  # 旧名行弃用
    kept = [ln for ln in lines[1:] if ln.strip() and ln.split(",")[0] not in ids]
    with open(REGISTRY, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(header.split(","))
        for ln in kept:
            w.writerow(ln.split(","))
        for r in REGISTRY_ROWS:
            w.writerow(r)
    print(f"[registry] refreshed {len(REGISTRY_ROWS)} P0 entries (stale rows replaced)")


# ══════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════
def main() -> int:
    P0_DIR.mkdir(parents=True, exist_ok=True)
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    ab, ws = load()
    cons = build_consolidated(ab, ws)

    # JSON
    (P0_DIR / "p0_consolidated.json").write_text(
        json.dumps(cons, indent=2, default=float), encoding="utf-8")

    # CSV (flat)
    csv_path = P0_DIR / "p0_consolidated.csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["domain", "wavelet_or_case", "model", "GER_mean", "S_full_mean",
                    "S_full_mode", "S_full_correct", "S_coh_mean"] + [f"E_{b}" for b in BANDS_CF])
        for c in CASES:
            d = cons["p0_1"]["cases"][c]
            w.writerow(["analytical_benchmark", c, "-", round(d["GER_mean"], 4),
                        round(d["S_full_mean"], 2), d["expected_S_full"],
                        round(d["S_full_correct_frac"], 3),
                        round(d["S_coh_mean"], 2) if d["S_coh_mean"] else "NA"]
                       + [round(d["E_direct_mean"][b], 4) for b in BANDS_CF])
        for wt in WAVELETS:
            for m in MODELS:
                d = cons["p0_2"]["real_nc"][wt][m]
                w.writerow(["wavelet_sensitivity", wt, m, round(d["GER_mean"], 4),
                            round(d["S_full_mean"], 2), d["S_full_mode"], "NA",
                            d["S_coh_mode"]]
                           + [round(d["E_direct_mean"][b], 4) for b in BANDS_CF])

    # YAML facts
    (P0_DIR / "p0_facts.yaml").write_text(build_facts_yaml(cons), encoding="utf-8")

    # LaTeX tables
    (TABLES_DIR / "tab_analytical_benchmark.tex").write_text(
        table_analytical_benchmark(cons), encoding="utf-8")
    (TABLES_DIR / "tab_wavelet_family_sensitivity.tex").write_text(
        table_wavelet_sensitivity(cons), encoding="utf-8")

    # README (flat: name-prefixed to avoid clobbering build/data/
    (P0_DIR / "p0_patch_README.md").write_text(README, encoding="utf-8")

    # Registry
    update_registry()

    # console summary
    print("=" * 78)
    print("  P0 CONSOLIDATION — package written")
    print("=" * 78)
    for p in sorted(P0_DIR.glob("p0_*")):
        print(f"  [data ] {p.relative_to(_PROJECT_ROOT)}")
    for t in ["tab_analytical_benchmark.tex", "tab_wavelet_family_sensitivity.tex"]:
        print(f"  [table] { (TABLES_DIR / t).relative_to(_PROJECT_ROOT) }")
    print("  [figs ] build/figures/fig_analytical_benchmark.{pdf,png}")
    print("          build/figures/fig_wavelet_sensitivity.{pdf,png}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
